config/routes.rb
LiveQuestionApp::Application.routes.draw do
  match "/users/login" => "users#login"        #to redirect to login page first and not a user of id name login
  match "/users/signIn" => "users#signIn"
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/users/display" => "users#display"
  resources :comment_votes

  resources :votes

  resources :comments

  resources :posts

  resources :users

  root :to => 'users#login'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  def authenticate (username, pwd)
     if self.uname == username && self.password == pwd
        return true
     else
        return false
     end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  #GET /users/display
  def display
    @users = User.all
    @resultArray= Array.new
    for user in @users do
      @result = user.name
      @posts = Post.find_all_by_user_id(user.id)
      for post in @posts do
        temp = Array.new
        @posts_ques =  post.question
        @comments = Comment.find_all_by_post_id(post.id)
        @comments_array = Array.new
        for comment in @comments do
          @comments_array << comment.reply
        end
        temp << @result << @posts_ques << @comments_array #for every user, find user name, hi
        @resultArray << temp
      end

    end
    respond_to do |format|
      format.html # display.html.erb
      format.json { render json: @resultArray }
    end

  end

  #GET /users/login
  def login
    respond_to do  |format|
      format.html #login.html.erb
    end
  end
  # GET /users/login
  # GET /users/login.json
  def signIn
    @user = User.find_by_uname(params[:uname])
    if @user == nil || !@user.authenticate(params[:uname], params[:password])
      redirect_to :action => "login", :notice => "Unable to log in to the system. Please check your credentials"
    elsif @user.authenticate(params[:uname], params[:password])
      session[:current_user_id] = @user.id
      redirect_to @user
    end

  end
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @sessionname = session[:current_user_id]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def search
     @users = User.find_all_by_name(params[:inp])
   #  @posts = Post.find_by_user_id(@users.id)

      if @users != nil
        respond_to do |format|
          format.html #search.html.erb
          format.json { render json: @users }
        end
      end
    #elsif (params[:search]== 'post')
          #redirect_to :controller => "posts", :action => "search"
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %><br />
    <%= f.text_field :uname %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :admin_perm %><br />
    <%= f.check_box :admin_perm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/display.html.erb
<div style="background-color: #007700; height:40px;"><p style="text-indent:25px;padding-top: 5px; color:white; font-family: Verdana; font-size: 18px; font-weight: bold;">     Live Question Tool App: CSC 517 </p> </div>


<table>
  <tr>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>
 <% @resultArray.each do |result| %>
    <tr>
      <td>
        <%= result %> <br/>
      </td>
    </tr>
  <% end %>
<br />

<%= link_to 'New Post', new_post_path %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uname</th>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Admin perm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uname %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.admin_perm %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div style="background-color: #007700; height:40px;"><p style="text-indent:25px;padding-top: 5px; color:white; font-family: Verdana; font-size: 18px; font-weight: bold;">     Live Question Tool App: CSC 517 </p> </div>
     <br/><br/>
<div style="margin-right: 350px; margin-left: 350px; text-padding:20px;  background-color: #F5F5F0;font-size: 14px; color: #007700;">
    <p align="center">Search for posts:
    <form action="/users/search" align="center"  method="get" id="search_form">
      <input id="search_input" type="text" name="inp"/> <input type="submit"  id="user"  name="usearch" value="user"/> <input type="submit" id="post" name="psearch" value="post" />
    </form>
    </p>
  <br/>
</div>
<h4 style="color:#007700;">Live Question App Login</h4>
<div style="background-color: #F5F5F0; width: 350px; height: 170px; border-top: 1px solid #007700; border-bottom:1px solid #007700; ">
  <form action="/users/signIn" method="get">
    <br/><b>User ID: </b>  <br/>
    <input type="text" name="uname" style="width: 140px;"/>
    <br/>
    <b> Password: </b>  <br/>
    <input type="password" name="password" style="width: 140px;"/>
    <br/>  <br/>
    <input type="submit" value="Sign in"/>   <%= link_to 'New User', new_user_path %>  <span style="font-size: 7pt;">(Sign up here for a new account)</span>
  </form>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uname</th>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Admin perm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uname %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.admin_perm %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= @sessionname %>
<p>
  <b>Uname:</b>
  <%= @user.uname %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Admin perm:</b>
  <%= @user.admin_perm %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>