config/routes.rb
LiveQuestionApp::Application.routes.draw do
  match "/users/login" => "users#login"        #to redirect to login page first and not a user of id name login
  match "/users/signIn" => "users#signIn"
  match "/users/search" => "users#search"
  match "/posts/search" => "posts#search"
  match "/users/display" => "users#display"
  resources :comment_votes

  resources :votes

  resources :comments

  resources :posts

  resources :users

  root :to => 'users#login'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_many :votes


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def search
    @posts = Post.find(:all, :conditions => "question LIKE '%#{params[:inp]}%'")
    #@posts = Post.where("question LIKE ?","%"+(params[:inp])+"%")
    if @posts != nil
      respond_to do |format|
        format.html # search.html.erb
        format.json { render json: @posts }
      end
    end
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @user= session[:current_user_id]
    if @user != nil  #if session id is set
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    else
      redirect_to :controller => "users", :action => "login" , :notice => "You have to login to post a question"
    end

  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create

     @user_id = session[:current_user_id]
     @post = Post.new()
     @post.user_id = @user_id
     @post.question = params[:post][:question]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: session[:current_user_id] }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style="background-color: #007700; height:40px;"><p style="text-indent:25px;padding-top: 5px; color:white; font-family: Verdana; font-size: 18px; font-weight: bold;">     Live Question Tool App: CSC 517 </p> </div>


<table>
  <tr>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td> </td>
    <td><%= post.question %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'New', new_comment_path(:post_id => post.id,:post_question => post.question) %></td>
    <td><% post.comments.each do |comment|%>
        <%= comment.reply %><br/>
        <% end %>
        </td>
  </tr>


<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<div style="background-color: #007700; height:40px;"><p style="text-indent:25px;padding-top: 5px; color:white; font-family: Verdana; font-size: 18px; font-weight: bold;">     Live Question Tool App: CSC 517 </p> </div>


<table>
  <tr>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.question %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @post.question %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>